const { Intents } = require('discord.js')

module.exports = {
    INTENTS: [Intents.FLAGS.GUILDS,Intents.FLAGS.GUILD_BANS,Intents.FLAGS.GUILD_EMOJIS_AND_STICKERS,Intents.FLAGS.GUILD_INTEGRATIONS,Intents.FLAGS.GUILD_INVITES,Intents.FLAGS.GUILD_MEMBERS,Intents.FLAGS.GUILD_MESSAGES,Intents.FLAGS.GUILD_MESSAGE_REACTIONS,Intents.FLAGS.GUILD_MESSAGE_TYPING,Intents.FLAGS.GUILD_PRESENCES,Intents.FLAGS.GUILD_VOICE_STATES,Intents.FLAGS.GUILD_WEBHOOKS],
    token: 'ODE0ODA1MTg2MTgxODU3Mjkw.YDjMdg.MKysujsr5GEhJO15jcvgjvJyO-I',
    id: '814805186181857290',
}